<ns0:RootFileSystem xmlns:ns0="https://www.linutronix.de/projects/Elbe" xmlns:xi="http://www.w3.org/2003/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" created="2009-05-20T08:50:56" revision="6" xsi:schemaLocation="https://www.linutronix.de/projects/Elbe dbsfed.xsd">
  <initvm>
    <buildtype>amd64</buildtype>
    <mirror>
      <primary_host>{{DEBIAN_MIRROR}}</primary_host>
      <primary_path>/debian</primary_path>
      <primary_proto>{{DEBIAN_MIRROR_PROTOCOL}}</primary_proto>
      <url-list>
        <url>
          <binary>
            http://debian.linutronix.de/elbe bullseye main
          </binary>
          <key>
            http://debian.linutronix.de/elbe/elbe-repo.pub
          </key>
        </url>
        <url>
          <binary>
            http://debian.linutronix.de/elbe-common bullseye main
          </binary>
          <key>
            http://debian.linutronix.de/elbe/elbe-repo.pub
          </key>
        </url>
      </url-list>
    </mirror>
    <suite>bullseye</suite>
    <pkg-list>
      <pkg>openssh-server</pkg>
    </pkg-list>
    <portforwarding>
      <forward>
        <proto>tcp</proto>
        <buildenv>22</buildenv>
        <host>5022</host>
      </forward>
      <forward>
        <proto>tcp</proto>
        <buildenv>7588</buildenv>
        <host>7587</host>
      </forward>
    </portforwarding>
  </initvm>
  <project>
    <name>{{PROJECT}}</name>
    <version>1.0</version>
    <description>
      For Olimex, Banana-Pi and Orange-Pi Boards
    </description>
    <buildtype>{{DEBARCH}}</buildtype>
    <mirror>
      <primary_host>{{DEBIAN_MIRROR_HOST}}</primary_host>
      <primary_path>{{DEBIAN_MIRROR_PATH}}</primary_path>
      <primary_proto>{{DEBIAN_MIRROR_PROTOCOL}}</primary_proto>
      <url-list>
        <url>
          <binary>
            {{DEBIAN_SECURITY_MIRROR_PROTOCOL}}://{{DEBIAN_SECURITY_MIRROR_HOST}}{{DEBIAN_SECURITY_MIRROR_PATH}} {{DEBIANSUITE}}{{DEBIAN_SECURITY_MIRROR_SUITE_SUFFIX}} main
          </binary>
          <source>
            {{DEBIAN_SECURITY_MIRROR_PROTOCOL}}://{{DEBIAN_SECURITY_MIRROR_HOST}}{{DEBIAN_SECURITY_MIRROR_PATH}} {{DEBIANSUITE}}{{DEBIAN_SECURITY_MIRROR_SUITE_SUFFIX}} main
          </source>
        </url>
        <url>
          <binary>
            {{DEBIAN_VOLATILE_MIRROR_PROTOCOL}}://{{DEBIAN_VOLATILE_MIRROR_HOST}}{{DEBIAN_VOLATILE_MIRROR_PATH}} {{DEBIANSUITE}}{{DEBIAN_VOLATILE_MIRROR_SUITE_SUFFIX}} main
          </binary>
          <source>
            {{DEBIAN_VOLATILE_MIRROR_PROTOCOL}}://{{DEBIAN_VOLATILE_MIRROR_HOST}}{{DEBIAN_VOLATILE_MIRROR_PATH}} {{DEBIANSUITE}}{{DEBIAN_VOLATILE_MIRROR_SUITE_SUFFIX}} main
          </source>
        </url>
        <!--
        <url>
          <binary>
            http://debian.linutronix.de/elbe {{DEBIANSUITE}} main
          </binary>
          <key>
            http://debian.linutronix.de/elbe/elbe-repo.pub
          </key>
        </url>
        <url>
          <binary>
            http://debian.linutronix.de/elbe-common {{DEBIANSUITE}} main
          </binary>
          <key>
            http://debian.linutronix.de/elbe/elbe-repo.pub
          </key>
        </url>
        -->
        <url>
          <binary>
            {{WEBSERVER_URL}} {{DEBIANSUITE}} main
          </binary>
          <source>
            {{WEBSERVER_URL}} {{DEBIANSUITE}} main
          </source>
          <key>
            {{WEBSERVER_URL}}/pubring.asc
          </key>
        </url>
      </url-list>
    </mirror>
    <noauth/>
    <suite>{{DEBIANSUITE}}</suite>
  </project>
  <target>
    <hostname>{{HOST_NAME}}</hostname>
    <domain>local</domain>
    <!-- xyzzy -->
    <passwd_hashed>$6$rounds=6500$JeQ0Z.AcT31/8QuA$eqXqkb5QjESmlgryNY.lj60K/Bnzt62gsYhDg6U8g/GYCD7qKELIYWTTjM0qXChaXdiOhG.STouJ4wzGl4Yvv/</passwd_hashed>
    <console>ttyAMA0,115200</console>
    <package>
      <tar>
        <name>nfsroot.tar.gz</name>
      </tar>
    </package>
    <images>
      <msdoshd>
        <name>sdcard.img</name>
        <size>{{SDCARD_SIZE}}</size>
        <binary offset="8" blocksize="1024">u-boot.bin</binary>
        <partition>
            <size>20MiB</size>
            <label>boot</label>
            <bootable/>
        </partition>
        <partition>
            <size>remain</size>
            <label>rootfs</label>
        </partition>
      </msdoshd>
    </images>
    <fstab>
      <bylabel>
        <label>rootfs</label>
        <mountpoint>/</mountpoint>
        <fs>
          <type>ext4</type>
          <tune2fs>-i 0</tune2fs>
        </fs>
      </bylabel>
      <bylabel>
        <label>boot</label>
        <mountpoint>/boot</mountpoint>
        <fs>
          <type>vfat</type>
        </fs>
      </bylabel>
      <bydev>
        <source>sysfs</source>
        <mountpoint>/sys</mountpoint>
        <fs>
          <type>sysfs</type>
        </fs>
        <options>rw,nosuid,nodev,noexec,relatime</options>
      </bydev>
      <bydev>
        <source>devpts</source>
        <mountpoint>/dev/pts</mountpoint>
        <fs>
          <type>devpts</type>
        </fs>
        <options>rw,nosuid,noexec,relatime,mode=620</options>
      </bydev>
      <bydev>
        <source>proc</source>
        <mountpoint>/proc</mountpoint>
        <fs>
          <type>proc</type>
        </fs>
      </bydev>
      <bydev>
        <source>tmpfs</source>
        <mountpoint>/tmp</mountpoint>
        <fs>
          <type>tmpfs</type>
        </fs>
        <options>size=4m</options>
      </bydev>
      <bydev>
        <source>tmpfs</source>
        <mountpoint>/var/log</mountpoint>
        <fs>
          <type>tmpfs</type>
        </fs>
        <options>size=2m</options>
      </bydev>
      <bydev>
        <source>tmpfs</source>
        <mountpoint>/var/lib/dhcp</mountpoint>
        <fs>
          <type>tmpfs</type>
        </fs>
        <options>size=1m</options>
      </bydev>
    </fstab>
    <install-recommends/>
    <finetuning>
      <rm>/var/cache/apt/archives/*.deb</rm>
      <rm>/etc/udev/rules.d/70-persistent-net.rules</rm>
      <t2p_mv path="/u-boot.bin">u-boot.bin</t2p_mv>
      <cp path="/usr/lib/linux-image-{{KERNELRELEASE}}/{{DTB}}.dtb">/boot/linux.dtb</cp>
    </finetuning>
    <pkg-list>
      <pkg>bash</pkg>
      <pkg>python3</pkg>
      <pkg>python3-dev</pkg>
      <pkg>git</pkg>
      <pkg>nfs-common</pkg>
      <pkg>openssh-server</pkg>
      <pkg>less</pkg>
      <!-- not found
      <pkg>ntp</pkg>
      -->
      <pkg>rsyslog</pkg>
      <pkg>logrotate</pkg>
      <pkg>ifupdown</pkg>
      <pkg>libc-bin</pkg>
      <pkg>isc-dhcp-client</pkg>
      <pkg>dash</pkg>
      <pkg>udev</pkg>
      <pkg>minicom</pkg>
      <pkg>u-boot-tools</pkg>
      <pkg>vlan</pkg>
      <pkg>vim-nox</pkg>
      <pkg>wget</pkg>
      <pkg>bind9-host</pkg>
      <pkg>linux-image-{{KERNELRELEASE}}</pkg>
      {% for pkg in pkglist -%}
      <pkg>{{pkg}}</pkg>
      {% endfor %}
    </pkg-list>
  </target>
</ns0:RootFileSystem>
