#!/usr/bin/python3

import os
import sys
from jinja2 import Environment, FileSystemLoader

env = Environment \
    ( loader        = FileSystemLoader ('.')
    , trim_blocks   = False
    , lstrip_blocks = False
    )

env.globals = os.environ

for fn in sys.argv [1:] :
    base, ext = os.path.splitext (fn)
    outfn = base + '.' + 'tmp'
    with open (outfn, 'w') as f :
        tpl = env.get_template (fn)
        f.write (tpl.render ())
