<pkg-list>
  <pkg>python</pkg>
  <pkg>python-dev</pkg>
  <pkg>python3</pkg>
  <pkg>python3-dev</pkg>
  <pkg>git</pkg>
  <pkg>nfs-common</pkg>
  <pkg>openssh-server</pkg>
  <pkg>less</pkg>
  <pkg>ntp</pkg>
  <pkg>rsyslog</pkg>
  <pkg>logrotate</pkg>
  <pkg>ifupdown</pkg>
  <pkg>libc-bin</pkg>
  <pkg>isc-dhcp-client</pkg>
  <pkg>dash</pkg>
  <pkg>udev</pkg>
  <pkg>minicom</pkg>
  <pkg>u-boot-tools</pkg>
  <pkg>vlan</pkg>
  <pkg>vim-nox</pkg>
  <pkg>wget</pkg>
  <pkg>bluez</pkg>
  <pkg>host</pkg>
